#!/usr/bin/env bash

# author: Duane Johnson
# email: duane.johnson@gmail.com
# date: 2008 Jun 12
# license: MIT
#
# Based on discussion at http://kerneltrap.org/mailarchive/git/2007/11/12/406496

# 2024-06-19: replaced recursive directory search with $git_root, djotto

# Find root of git repo
git_root=$(git rev-parse --show-toplevel 2>/dev/null)

if [ -n "$git_root" ]; then
  config_file="$git_root/.git/config"

  echo "== Configuration ($config_file)"
  cat "$config_file"
  echo

  echo "== Remote URLs:"
  git remote -v
  echo

  echo "== Remote Branches: "
  git branch -r
  echo

  echo "== Local Branches:"
  git branch
  echo

  echo "== Most Recent Commit"
  git --no-pager log --max-count=1
  echo

  echo "Type 'git lg' for more commits, or 'git show' for full commit details."
else
  echo "Not a git repository."
fi

