#!/usr/bin/env dash

# author: Duane Johnson
# email: duane.johnson@gmail.com
# date: 2008 Jun 12
# license: MIT
#
# Based on discussion at http://kerneltrap.org/mailarchive/git/2007/11/12/406496

# 2024-06-19 replaced recursive directory search with $git_root, djotto
# 2024-06-23 exit with error if not in a git repo, djotto
# 2024-07-03 add -vv to `git branch` calls, djotto
# 2024-07-04 replace spooling config file with calling 'git config'

# Find root of git repo
git_root=$(git rev-parse --show-toplevel 2>/dev/null)

if [ -n "$git_root" ]; then
  echo "## Local configuration"
  git config --local --list
  echo

  echo "## Remote URLs:"
  git remote -v
  echo

  echo "## Remote branches: "
  git branch -vv -r
  echo

  echo "## Local branches:"
  git branch -vv
  echo

  echo "## Most recent commit"
  git --no-pager log --max-count=1
  echo

  echo "Type 'git lg' for more commits, or 'git show' for full commit details."
else
  echo "Not a git repository."
  exit 1
fi
